"""Initial tables

Revision ID: 155e776f6580
Revises: eeb3d886eba3
Create Date: 2025-12-10 13:58:44.771281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155e776f6580'
down_revision: Union[str, Sequence[str], None] = 'eeb3d886eba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_statistics', sa.Column('revenue', sa.Float(), nullable=True, comment='Latest TTM Revenue for Aggregation'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_statistics', 'revenue')
    # ### end Alembic commands ###
