"""Initial tables

Revision ID: eeb3d886eba3
Revises: fda80b6a1a4f
Create Date: 2025-12-09 15:40:53.144742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb3d886eba3'
down_revision: Union[str, Sequence[str], None] = 'fda80b6a1a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_aggregations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('avg_pe_ratio', sa.Float(), nullable=True, comment='Mean PE ratio across all tickers'),
    sa.Column('avg_revenue_growth', sa.Float(), nullable=True, comment='Mean revenue growth across all tickers'),
    sa.Column('sum_revenue', sa.Float(), nullable=True, comment='Sum revenue across all tickers'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry')
    )
    op.create_table('ticker_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True, comment='Price-to-Earnings ratio (Last Quarter)'),
    sa.Column('revenue_growth', sa.Float(), nullable=True, comment='QoQ Revenue Growth'),
    sa.Column('net_income_ttm', sa.Float(), nullable=True, comment='Trailing Twelve Months Net Income'),
    sa.Column('debt_ratio', sa.Float(), nullable=True, comment='Debt-to-Equity ratio (Last Year)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_statistics_symbol'), 'ticker_statistics', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_statistics_symbol'), table_name='ticker_statistics')
    op.drop_table('ticker_statistics')
    op.drop_table('industry_aggregations')
    # ### end Alembic commands ###
